plugins {
	id 'java'
	id 'application'
	id 'org.jetbrains.kotlin.jvm' version '1.9.23'
	id 'org.openjfx.javafxplugin' version '0.0.13'
	id 'org.javamodularity.moduleplugin' version '1.8.12'
}

group = 'ru.ravel'
version = '1.0-SNAPSHOT'

repositories {
	mavenCentral()
}

javafx {
	version = '21.0.2'
	modules = ['javafx.controls', 'javafx.fxml']
}

dependencies {
	implementation 'org.openjfx:javafx-controls:21.0.2'
	implementation 'org.openjfx:javafx-fxml:21.0.2'
	implementation "org.jetbrains.kotlin:kotlin-stdlib"
	implementation "com.fasterxml.jackson.module:jackson-module-kotlin:2.15.2"
	implementation "com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.15.2"
	implementation "org.codehaus.groovy:groovy:3.0.24"
	implementation "org.codehaus.groovy:groovy-jsr223:3.0.24"
	implementation 'com.fasterxml.jackson.core:jackson-databind:2.19.0'
}

application {
	mainClass = 'ru.ravel.testjavafx.HelloApplicationKt'
}

java {
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
	modularity.inferModulePath = true
}

tasks.named('compileKotlin', org.jetbrains.kotlin.gradle.tasks.KotlinCompile) {
	kotlinOptions.jvmTarget = '21'
	destinationDirectory.set(
			tasks.named('compileJava', JavaCompile).get().destinationDirectory
	)

//	toolchain {
//		languageVersion = JavaLanguageVersion.of(21)
//	}
}
tasks.named('compileTestKotlin', org.jetbrains.kotlin.gradle.tasks.KotlinCompile) {
	kotlinOptions.jvmTarget = '21'
	destinationDirectory.set(
			tasks.named('compileTestJava', JavaCompile).get().destinationDirectory
	)
}

jar {
	manifest {
		attributes(
				'Main-Class': 'ru.ravel.testjavafx.MainApp'
		)
	}
	from {
		configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
	}
	duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

mainClassName = 'ru.ravel.testjavafx.MainApp'


tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
	kotlinOptions {
		jvmTarget = "21" // или 17 — под вашу Java
	}
}