plugins {
	id 'java'
	id 'application'
	id 'org.jetbrains.kotlin.jvm' version '1.9.23'
	id 'org.openjfx.javafxplugin' version '0.0.13'
	id 'org.javamodularity.moduleplugin' version '1.8.12'
}

group = 'ru.ravel'
version = '1.0-SNAPSHOT'

repositories { mavenCentral() }

def javaFxVersion = '21.0.2'

javafx {
	version = javaFxVersion
	modules = ['javafx.controls', 'javafx.fxml']
}

dependencies {
	implementation "org.jetbrains.kotlin:kotlin-stdlib"
}

application {
	mainClass = 'ru.ravel.testjavafx.HelloApplicationKt'
}

java {
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
	modularity.inferModulePath = true
}

tasks.named('compileKotlin', org.jetbrains.kotlin.gradle.tasks.KotlinCompile) {
	kotlinOptions.jvmTarget = '21'
	destinationDirectory.set(
			tasks.named('compileJava', JavaCompile).get().destinationDirectory
	)
}
tasks.named('compileTestKotlin', org.jetbrains.kotlin.gradle.tasks.KotlinCompile) {
	kotlinOptions.jvmTarget = '21'
	destinationDirectory.set(
			tasks.named('compileTestJava', JavaCompile).get().destinationDirectory
	)
}