pluginManagement {
	repositories {
		google()
		mavenCentral()
		gradlePluginPortal()
	}
}

plugins {
	id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

dependencyResolutionManagement {
	repositoriesMode.set(RepositoriesMode.PREFER_PROJECT)
	repositories {
		google()
		mavenCentral()
		gradlePluginPortal()
	}
}

rootProject.name = "low-code-processes-executor"

include(":core", ":desktop", ":android")
project(":core").projectDir = file("core")
project(":desktop").projectDir = file("desktop")
project(":android").projectDir = file("android")