plugins {
	id 'com.android.library'
	id 'org.jetbrains.kotlin.android'
}

android {
	namespace "ru.ravel.lcpeandroid"
	compileSdk 35

	defaultConfig {
		minSdk = 26
		targetSdk 34
		consumerProguardFiles("consumer-rules.pro")
	}

	buildTypes {
		release {
			minifyEnabled = false
			proguardFiles(
				getDefaultProguardFile("proguard-android-optimize.txt"),
				"proguard-rules.pro"
			)
		}
	}

	// важно — убираем всё лишнее из паковки
	publishing {
		singleVariant("release")
	}
}

dependencies {
//	implementation project(":core")
	implementation files("../core/build/libs/core-thin.jar")
}