plugins {
	id 'com.android.library'
	id 'org.jetbrains.kotlin.android'
}

android {
	namespace "ru.ravel.lcpeandroid"
	compileSdk 34

	defaultConfig {
		minSdk 24
		targetSdk 34
	}

	compileOptions {
		sourceCompatibility JavaVersion.VERSION_21
		targetCompatibility JavaVersion.VERSION_21
	}

	kotlinOptions {
		jvmTarget = "21"
	}

//	sourceSets {
//		main {
//			java.srcDirs += ['../core/src/main/kotlin']
//			resources.srcDirs += ['../core/src/main/resources']
//		}
//	}

	buildTypes {
		release { minifyEnabled false }
		debug { minifyEnabled false }
	}
}

dependencies {
	implementation files("../core/build/libs/core-all.jar")
	implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.9.0'
	implementation "org.mozilla:rhino:1.7.14"
	implementation "org.python:jython-standalone:2.7.3"
}