plugins {
	id 'org.jetbrains.kotlin.jvm'
	id 'java-library'
	id 'com.github.johnrengelman.shadow' version '8.1.1'
}

java {
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
	toolchain { languageVersion = JavaLanguageVersion.of(21) }
	withSourcesJar()
}

dependencies {
	implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.9.0'
	implementation 'com.fasterxml.jackson.core:jackson-databind:2.20.0'
	implementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.20.0'
	implementation 'com.fasterxml.jackson.module:jackson-module-kotlin:2.20.0'
	implementation 'org.yaml:snakeyaml:2.5'
}

tasks.register('thinJar', Jar) {
	archiveClassifier.set('thin')
	from(sourceSets.main.output)
}